In [8]:
import numpy as np

np.set_printoptions(suppress=True)

b0, b1, b2, b3 = beta
print("\nbeta = [b0, b1, b2, b3] =",
      np.array2string(beta, formatter={'float_kind':lambda z: f'{z:.10f}'}))

# Pretty-print the polynomial
print("\nLeast-squares cubic:")
print(f"y(t) = {b0:.10f} + {b1:.10f} t + {b2:.10f} t^2 + {b3:.10f} t^3")

# If you want rounded-to-4dp like the solution key:
print("\nRounded to 4 d.p.:")
print(f"y(t) ≈ {b0:.4f} + {b1:.4f} t + {b2:.4f} t^2 + {b3:.4f} t^3")

# Data
t = np.arange(0, 13, dtype=float)
y = np.array([0.0, 8.8, 29.9, 62.0, 104.7, 159.1, 222.0,
              294.5, 380.4, 471.1, 571.7, 686.8, 809.2], dtype=float)

# Design matrix
X = np.column_stack([np.ones_like(t), t, t**2, t**3])

# Normal equations
XT, XTX, XTy = X.T, X.T @ X, X.T @ y

# Power sums (to verify 78, 650, 6084, …)
S1   = t.size
St   = t.sum()
St2  = (t**2).sum()
St3  = (t**3).sum()
St4  = (t**4).sum()
St5  = (t**5).sum()
St6  = (t**6).sum()
Sy   = y.sum()
Sty  = (t*y).sum()
St2y = ((t**2)*y).sum()
St3y = ((t**3)*y).sum()

def matprint(M, name):
    import numpy as _np
    print(f"\n{name} =")
    print(_np.array2string(_np.asarray(M), formatter={'float_kind':lambda z: f'{z:.10g}'}))

print("=== Least-Squares Cubic Fit: y = b0 + b1 t + b2 t^2 + b3 t^3 ===")
print(f"N = {t.size}")
print("t =", t)
print("y =", y)
matprint(X,   "Design matrix X")
matprint(XTX, "X^T X")
matprint(XTy, "X^T y")

print("\nPower sums:")
print(f"∑1   = {S1}")
print(f"∑t   = {St}")
print(f"∑t^2 = {St2}")
print(f"∑t^3 = {St3}")
print(f"∑t^4 = {St4}")
print(f"∑t^5 = {St5}")
print(f"∑t^6 = {St6}")
print(f"∑y      = {Sy:.10g}")
print(f"∑t·y    = {Sty:.10g}")
print(f"∑t^2·y  = {St2y:.10g}")
print(f"∑t^3·y  = {St3y:.10g}")

# Solve for beta
beta = np.linalg.solve(XTX, XTy)
b0, b1, b2, b3 = beta
print("\nβ = [b0, b1, b2, b3] =", np.array2string(beta, formatter={'float_kind':lambda z: f'{z:.10g}'}))

# Fit stats
y_hat = X @ beta
resid = y - y_hat
SSE = float(np.sum(resid**2))
SST = float(np.sum((y - y.mean())**2))
R2  = 1.0 - SSE / SST
print("\nGoodness of fit:")
print(f"SSE = {SSE:.10g}")
print(f"R^2 = {R2:.10g}")

# Velocity at t=4.5
def v_of_t(tval): return b1 + 2*b2*tval + 3*b3*(tval**2)
print(f"\nVelocity at t=4.5 s: v(4.5) = {float(v_of_t(4.5)):.10g} ft/s")

# Try plotting if matplotlib is present
try:
    import matplotlib.pyplot as plt
    tt = np.linspace(t.min(), t.max(), 400)
    Xtt = np.column_stack([np.ones_like(tt), tt, tt**2, tt**3])
    y_fit_curve = Xtt @ beta
    v_curve = v_of_t(tt)

    plt.figure()
    plt.scatter(t, y, label="data")
    plt.plot(tt, y_fit_curve, label="cubic fit")
    plt.xlabel("time t (s)")
    plt.ylabel("position y (ft)")
    plt.title("Position data and least-squares cubic fit")
    plt.legend()
    plt.show()

    plt.figure()
    plt.plot(tt, v_curve, label="velocity v(t)")
    plt.axvline(4.5, linestyle="--")
    plt.axhline(v_of_t(4.5), linestyle="--")
    plt.xlabel("time t (s)")
    plt.ylabel("velocity (ft/s)")
    plt.title("Velocity from fitted cubic (derivative)")
    plt.legend()
    plt.show()
except ModuleNotFoundError:
    print("\n(matplotlib not installed in this kernel — skipping plots.)")



beta = [b0, b1, b2, b3] = [-0.8557692308 4.7024850150 5.5553696304 -0.0273601399]

Least-squares cubic:
y(t) = -0.8557692308 + 4.7024850150 t + 5.5553696304 t^2 + -0.0273601399 t^3

Rounded to 4 d.p.:
y(t) ≈ -0.8558 + 4.7025 t + 5.5554 t^2 + -0.0274 t^3
=== Least-Squares Cubic Fit: y = b0 + b1 t + b2 t^2 + b3 t^3 ===
N = 13
t = [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
y = [  0.    8.8  29.9  62.  104.7 159.1 222.  294.5 380.4 471.1 571.7 686.8
 809.2]

Design matrix X =
[[1 0 0 0]
 [1 1 1 1]
 [1 2 4 8]
 [1 3 9 27]
 [1 4 16 64]
 [1 5 25 125]
 [1 6 36 216]
 [1 7 49 343]
 [1 8 64 512]
 [1 9 81 729]
 [1 10 100 1000]
 [1 11 121 1331]
 [1 12 144 1728]]

X^T X =
[[13 78 650 6084]
 [78 650 6084 60710]
 [650 6084 60710 630708]
 [6084 60710 630708 6735950]]

X^T y =
[3800.2 35127.7 348063.9 3599800.9]

Power sums:
∑1   = 13
∑t   = 78.0
∑t^2 = 650.0
∑t^3 = 6084.0
∑t^4 = 60710.0
∑t^5 = 630708.0
∑t^6 = 6735950.0
∑y      = 3800.2
∑t·y    = 35127.7
∑t^2·y  = 348063.9
∑t^3·y  = 3599800.9