# Orthogonal Columns Demo
This notebook extracts matrix $A$ from the exercise, computes $A^\top A$ to check orthogonality, and uses QR decomposition to obtain an orthonormal basis for the columns.

In [2]:
import numpy as np

A = np.array([
    [-6, -3,  6,  1],
    [-1,  2,  1, -6],
    [ 3,  6,  3, -2],
    [ 6, -3,  6, -1],
    [ 2, -1,  2,  3],
    [-3,  6,  3,  2],
    [-2, -1,  2, -3],
    [ 1,  2,  1,  6]
])
A

array([[-6, -3,  6,  1],
       [-1,  2,  1, -6],
       [ 3,  6,  3, -2],
       [ 6, -3,  6, -1],
       [ 2, -1,  2,  3],
       [-3,  6,  3,  2],
       [-2, -1,  2, -3],
       [ 1,  2,  1,  6]])

In [3]:
# Compute A^T A (Gram matrix). If columns of A are orthogonal, this should be diagonal.
Gram = A.T @ A
Gram

array([[100,   0,   0,   0],
       [  0, 100,   0,   0],
       [  0,   0, 100,   0],
       [  0,   0,   0, 100]])

In [4]:
# QR decomposition to obtain an orthonormal basis for the columns of A
Q, R = np.linalg.qr(A)
Q, R

(array([[-0.6,  0.3, -0.6,  0.1],
        [-0.1, -0.2, -0.1, -0.6],
        [ 0.3, -0.6, -0.3, -0.2],
        [ 0.6,  0.3, -0.6, -0.1],
        [ 0.2,  0.1, -0.2,  0.3],
        [-0.3, -0.6, -0.3,  0.2],
        [-0.2,  0.1, -0.2, -0.3],
        [ 0.1, -0.2, -0.1,  0.6]]),
 array([[ 1.00000000e+01,  1.66533454e-16, -3.33066907e-16,
         -5.55111512e-17],
        [ 0.00000000e+00, -1.00000000e+01,  8.67361738e-16,
          1.11022302e-16],
        [ 0.00000000e+00,  0.00000000e+00, -1.00000000e+01,
          1.55621005e-17],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+01]]))

In [5]:
# Verify orthonormality: Q^T Q should be the identity matrix
np.allclose(Q.T @ Q, np.eye(Q.shape[1]))

True